### ISSUE TITLE
Try to remove duplicated branches during processing to save memory

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/MuonBDTPid#5]
We are adding `TupleToolANNPIDTraining`, and this TupleTool will add some existing branches. This is undesirable as we/the experts want to reduce memory consumption.

**Comment by yipengsun** [comment]
The `TupleToolANNPIDTraining` source code is available [here](https://gitlab.cern.ch/lhcb/Analysis/blob/c1bb6d7a200a7aa512ad77c77676f2c46c8bb219/Phys/DecayTreeTupleANNPID/src/TupleToolANNPIDTraining.cpp).

The source for the underlying TupleTool that gets called is [here](https://gitlab.cern.ch:8443/lhcb/Rec/-/blob/1183578a95b14c158942c8f016e64b953ad45cd6/Rec/ChargedProtoANNPID/src/ChargedProtoANNPIDTupleTool.cpp).

**Comment by yipengsun** [comment]
I'm preparing a version of Castelao that doesn't add duplicated branches in runtime: https://gitlab.cern.ch/suny/Castelao

**Comment by yipengsun** [comment]
@manuelfs @Svende @afernez Here's my draft to the expert:

> Dear experts,
>
> I've made changes to Castelao so that only minimally required branches are added to PIDCalib samples.
>
> Here's what I changed:
> 1. Add a Gaudi module based on `Rec/ChargedProtoANNPIDTupleTool` to add minimally required branches for uBDT
>    https://gitlab.cern.ch:8443/lhcb/Rec/-/blob/1183578a95b14c158942c8f016e64b953ad45cd6/Rec/ChargedProtoANNPID
> 2. Add a `TupleToolANNPIDTrainingLight` tool to use the added Gaudi module
> 3. Add the TupleTool to probe Muons in `parseTupleConfig.py`.
>
> I've add these changes to my Castelao fork and if you think these changes are OK, I can create a pull request.
>    https://gitlab.cern.ch/suny/Castelao
>
> Here's some questions:
> 1. In my Gaudi module, I don't think TMVA is used. Can I also remove the TMVA code?
> 2. We still want to remove PT cuts for Muons globally, could you tell us if that's feasible, and if so, where should I make the change?
> 3. Could you reproduce the full PIDCalib samples centrally?

**Comment by yipengsun** [comment]
Also, my locally generated PIDCalib samples are available at:
```
/afs/cern.ch/user/s/suny/eos/pidcalib
```

Please help me check that these are accessible. 

Also, I've double checked the required branches, but I still want you to check them. All required branches are listed in [this file](https://github.com/umd-lhcb/MuonBDTPid/blob/7ef7a6b58179d39055efb585a435d6d0aca22938/src/AddUboostBranchRun2.cpp), you can see if all branches (the `isMuonTight` needs some prefix) are available in my PIDCalib sample ntuples.

**Comment by manuelfs** [comment]
Thank you Yipeng for writing this up. I'm not sure if I need to mount eos or something, but I cannot see your folder
```
|04:16:21|lxplus7107:~$ ll /afs/cern.ch/user/s/suny/eos/pidcalib
ls: cannot open directory /afs/cern.ch/user/s/suny/eos/pidcalib: Operation not permitted
|04:16:23|lxplus7107:~$ ll /afs/cern.ch/user/s/suny/eos
lrwxr-xr-x. 1 suny def-cg 16 Nov  8  2018 /afs/cern.ch/user/s/suny/eos -> /eos/home-s/suny
```

For the email, here's a few edits to make it more clear. I think it should be addressed to Vitalii, and see if he can take it from here (so no need of removing TMVA). Also, could you list the branches that this code adds in the first parenthesis or so?

===========

Dear Vitalii,

I've made changes to Castelao so that only minimally required branches (<list branches>) are added to PIDCalib samples. You can see the code here and if you think these changes are OK, I can create a pull request.
https://gitlab.cern.ch/suny/Castelao

Here's what I changed:

• I had to add a Gaudi module based on Rec/ChargedProtoANNPIDTupleTool to add the minimally required branches for uBDT
https://gitlab.cern.ch:8443/lhcb/Rec/-/blob/1183578a95b14c158942c8f016e64b953ad45cd6/Rec/ChargedProtoANNPID
• Added a TupleToolANNPIDTrainingLight tool to use the added Gaudi module
• Added the TupleTool to probe Muons in parseTupleConfig.py.

By the way, we still need to remove the PT cuts for all muon samples, and reduce the PT cut for hadrons at least to 250 MeV. Can this be done?

Let us know if anything else is needed and if it may be possible to do the full PIDCalib reprocessing centrally, thank you.

**Comment by yipengsun** [comment]
I already removed the TMVA and the output ntuple still look the same. I'll list branches added by this code.

**Comment by yipengsun** [comment]
I relocated the sample ntuples to:
```
/afs/cern.ch/user/s/suny/public/pidcalib
```

Would you test again to see if they are accessible now?

**Comment by afernez** [comment]
I tried accessing the sample ntuples, but I had similar permission issues as Manuel:
```
[afernez@lxplus785 ~]$ ls /afs/cern.ch/user/s/suny/public/
pidcalib
[afernez@lxplus785 ~]$ ls /afs/cern.ch/user/s/suny/public/pidcalib/
ls: cannot access /afs/cern.ch/user/s/suny/public/pidcalib/pidcalib_jpsi_orig.root: Permission denied
ls: cannot access /afs/cern.ch/user/s/suny/public/pidcalib/pidcalib_jpsi_ubdt_br.root: Permission denied
ls: cannot access /afs/cern.ch/user/s/suny/public/pidcalib/pidcalib_jpsi_ubdt_br_newer.root: Permission denied
pidcalib_jpsi_orig.root  pidcalib_jpsi_ubdt_br.root  pidcalib_jpsi_ubdt_br_newer.root
```

**Comment by yipengsun** [comment]
I think I've changed all directories to `777` and all files to `666`. Maybe it works now?? (The initial one doesn't work probably because it's on EOS, and it needs some separate tool to share. I tried the web interface but kept getting errors).

**Comment by afernez** [comment]
I still see the same permission denied messages. Looking up AFS access rights quickly, this could be relevant: I found [this page](https://information-technology.web.cern.ch/services/fe/afs/howto/configure-afs-access-rights) that seems to indicate that AFS (mostly) ignores UNIX permissions, instead using its own system of access control lists (ACLs). [This site](https://web.stanford.edu/~consult/afsinfo/basic.shtml) has better documentation for manipulating the ACLs- if you try 
`fs setacl /afs/cern.ch/user/s/suny/public/pidcalib system:anyuser read` (or replace system:anyuser with a username you want to share with)
it should (I hope) grant list/read (including copy) rights to the files in your `pidcalib` directory.

**Comment by yipengsun** [comment]
Done. Does it work now?

**Comment by yipengsun** [comment]
I grant the read permission to `/afs/cern.ch/user/s/suny/public`. I hope it makes every subdirectory automatically world-readable. Also, in addition to the `ls` test, could you also try to download one of the files?

**Comment by afernez** [comment]
I think only _new_ subdirectories inherit the parent directory's permissions. I still get permission denied for the files in the `pidcalib` directory when I `ls`, and when I `fs listacl`,
```
[afernez@lxplus7108 ~]$ fs listacl /afs/cern.ch/user/s/suny/public/pidcalib/
Access list for /afs/cern.ch/user/s/suny/public/pidcalib/ is
Normal rights:
  system:administrators rlidwka
  system:anyuser l
  suny rlidwka
[afernez@lxplus7108 ~]$ fs listacl /afs/cern.ch/user/s/suny/public/
Access list for /afs/cern.ch/user/s/suny/public/ is
Normal rights:
  system:administrators rlidwka
  system:anyuser rl
  suny rlidwka
```
so, I think you have to `fs setacl /afs/cern.ch/user/s/suny/public/pidcalib system:anyuser read` the `pidcalib` subdirectory manually.

**Comment by yipengsun** [comment]
Done. Now `pidcalib` does have the right ACL when using `fs listacl`. I'll send the email now.

**Comment by yipengsun** [comment]
We should document this permission fiasco in our ntuple-gen wiki.
